# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

@sms = System.find_by_name("Sega Master System")
unless @sms.nil?
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ace-of-aces", :title => "Ace of Aces")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/action-fighter", :title => "Action Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/addams-family___", :title => "The Addams Family")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/aerial-assault", :title => "Aerial Assault")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/after-burner", :title => "After Burner")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/air-rescue", :title => "Air Rescue")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-in-miracle-world", :title => "Alex Kidd in Miracle World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-in-shinobi-world", :title => "Alex Kidd in Shinobi World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-bmx-trial", :title => "Alex Kidd: BMX Trial")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-high-tech-world", :title => "Alex Kidd: High-Tech World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-the-lost-stars", :title => "Alex Kidd: The Lost Stars")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alf", :title => "ALF")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien-storm", :title => "Alien Storm")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien-syndrome", :title => "Alien Syndrome")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien_", :title => "Alien 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/altered-beast", :title => "Altered Beast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/andre-agassi-tennis", :title => "Andre Agassi Tennis")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/arcade-smash-hits", :title => "Arcade Smash Hits")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/as-aventuras-da-tv-colosso", :title => "As Aventuras da TV Colosso")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/assault-city", :title => "Assault City")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astro-warrior", :title => "Astro Warrior") 
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astro-warrior-pit-pot", :title => "Astro Warrior / Pit Pot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astrix_", :title => "Asterix")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astrix-and-the-great-rescue", :title => "Asterix and the Great Rescue")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ayrton-sennas-super-monaco-gp-ii", :title => "Ayrton Senna's Super Monaco GP II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/aztec-adventure", :title => "Aztec Adventure")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/back-to-the-future-part-ii", :title => "Back to the Future Part II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/back-to-the-future-part-iii", :title => "Back to the Future Part III")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/baku-baku-animal", :title => "Baku Baku Animal")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bank-panic", :title => "Bank Panic")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/batman-returns_______", :title => "Batman Returns")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/battle-out-run", :title => "Battle Out Run")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/battletoads-in-battlemaniacs", :title => "Battletoads in Battlemaniacs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/black-belt", :title => "Black Belt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/blade-eagle-3-d", :title => "Blade Eagle 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bomber-raid", :title => "Bomber Raid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bonanza-bros", :title => "Bonanza Bros.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bram-stokers-dracula__", :title => "Bram Stoker's Dracula")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bubble-bobble", :title => "Bubble Bobble")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/california-games", :title => "California Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/california-games-ii", :title => "California Games II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/captain-silver", :title => "Captain Silver")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chapolim-x-drcula-um-duelo-assustador", :title => "Chapolim x Dracula: Um Duelo Assustador")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chase-hq", :title => "Chase H.Q.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chase-hq-ii-special-criminal-investigation", :title => "Chase H.Q. II: Special Criminal Investigation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cheese-cat-astrophe-starring-speedy-gonzales", :title => "Cheese Cat-Astrophe starring Speedy Gonzales")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/choplifter", :title => "Choplifter!")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chuck-rock", :title => "Chuck Rock")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chuck-rock-ii-son-of-chuck", :title => "Chuck Rock II: Son of Chuck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cloud-master", :title => "Cloud Master")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/columns", :title => "Columns")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cool-spot", :title => "Cool Spot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cosmic-spacehead", :title => "Cosmic Spacehead")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cyber-shinobi-shinobi-part-2", :title => "The Cyber Shinobi: Shinobi Part 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cyborg-hunter", :title => "Cyborg Hunter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/danan-the-jungle-fighter", :title => "Danan the Jungle Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dead-angle", :title => "Dead Angle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/deep-duck-trouble-starring-donald-duck", :title => "Deep Duck Trouble starring Donald Duck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/desert-strike-return-to-the-gulf", :title => "Desert Strike: Return to the Gulf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/disneys-ariel-the-little-mermaid", :title => "Disney's Ariel the Little Mermaid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/disneys-bonkers-wax-up", :title => "Disney's Bonkers: Wax Up!")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/double-dragon", :title => "Double Dragon")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/double-hawk", :title => "Double Hawk")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dr-robotniks-mean-bean-machine", :title => "Dr. Robotnik's Mean Bean Machine")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dragon-crystal", :title => "Dragon Crystal")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dragon-the-bruce-lee-story_", :title => "Dragon: The Bruce Lee Story")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dynamite-duke", :title => "Dynamite Duke")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dynamite-headdy", :title => "Dynamite Headdy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/e-swat-cyber-police", :title => "E-SWAT: Cyber Police")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/earthworm-jim", :title => "Earthworm Jim")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ecco-the-dolphin", :title => "Ecco the Dolphin")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ecco-the-tides-of-time", :title => "Ecco: The Tides of Time")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/enduro-racer", :title => "Enduro Racer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/f16-fighting-falcon", :title => "F16 Fighting Falcon")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantastic-adventures-of-dizzy", :title => "The Fantastic Adventures of Dizzy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone", :title => "Fantasy Zone")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone-ii", :title => "Fantasy Zone II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone-the-maze", :title => "Fantasy Zone: The Maze")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fifa-international-soccer", :title => "FIFA International Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fire-forget-ii", :title => "Fire & Forget II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fire-ice", :title => "Fire & Ice")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/forgotten-worlds", :title => "Forgotten Worlds")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/g-loc-air-battle", :title => "G-Loc Air Battle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gain-ground", :title => "Gain Ground")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/galactic-protector", :title => "Galactic Protector")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-corridas", :title => "Game Box Serie Corridas")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-esportes", :title => "Game Box Serie Esportes")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-lutas", :title => "Game Box Serie Lutas")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gangster-town", :title => "Gangster Town")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gauntlet", :title => "Gauntlet")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/george-foremans-ko-boxing", :title => "George Foreman's KO Boxing")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghost-house", :title => "Ghost House")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghostbusters", :title => "Ghostbusters")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghouls-n-ghosts", :title => "Ghouls 'N Ghosts")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/global-defense", :title => "Global Defense")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/global-gladiators", :title => "Global Gladiators")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golden-axe", :title => "Golden Axe")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golden-axe-warrior", :title => "Golden Axe Warrior")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golvellius-valley-of-doom", :title => "Golvellius: Valley of Doom")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/great-volleyball", :title => "Great Volleyball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hang-on-safari-hunt", :title => "Hang On & Safari Hunt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hang-on", :title => "Hang-On")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/heroes-of-the-lance", :title => "Heroes of the Lance")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hokuto-no-ken_", :title => "Hokuto no Ken")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/impossible-mission", :title => "Impossible Mission")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/incredible-crash-dummies", :title => "The Incredible Crash Dummies")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/incredible-hulk_", :title => "The Incredible Hulk")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/indiana-jones-and-the-last-crusade-the-action-game", :title => "Indiana Jones and the Last Crusade: The Action ...")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ivan-iron-man-stewarts-super-off-road", :title => "Ivan 'Iron Man' Stewart's Super Off Road")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/james-bond-007-the-duel", :title => "James Bond 007: The Duel")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/james-pond-2-codename-robocod", :title => "James Pond 2: Codename: RoboCod")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/jungle-book_", :title => "The Jungle Book")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kenseiden", :title => "Kenseiden")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kings-quest", :title => "King's Quest")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/klax", :title => "Klax")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/krustys-fun-house", :title => "Krusty's Fun House")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kung-fu-kid", :title => "Kung Fu Kid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/land-of-illusion-starring-mickey-mouse", :title => "Land of Illusion starring Mickey Mouse")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/laser-ghost", :title => "Laser Ghost")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/legend-of-illusion-starring-mickey-mouse", :title => "Legend of Illusion starring Mickey Mouse")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lemmings", :title => "Lemmings")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lion-king", :title => "The Lion King")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lord-of-the-sword", :title => "Lord of the Sword")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lucky-dime-caper-starring-donald-duck", :title => "The Lucky Dime Caper starring Donald Duck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/marble-madness", :title => "Marble Madness")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/master-of-darkness", :title => "Master of Darkness")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/maze-hunter-3-d", :title => "Maze Hunter 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mercs", :title => "Mercs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/michael-jacksons-moonwalker", :title => "Michael Jackson's Moonwalker")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mickeys-ultimate-challenge", :title => "Mickey's Ultimate Challenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/micro-machines", :title => "Micro Machines")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/miracle-warriors-seal-of-the-dark-lord", :title => "Miracle Warriors: Seal of the Dark Lord")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/missile-defense-3-d", :title => "Missile Defense 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/monopoly", :title => "Monopoly")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/montezumas-revenge", :title => "Montezuma's Revenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat", :title => "Mortal Kombat")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat-3", :title => "Mortal Kombat 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat-ii", :title => "Mortal Kombat II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ms-pac-man", :title => "Ms. Pac-Man")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/my-hero", :title => "My Hero")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mnica-no-castelo-do-drago", :title => "Monica no Castelo do Dragao")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/new-zealand-story", :title => "The New Zealand Story")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ninja", :title => "The Ninja")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/olympic-gold-barcelona-92", :title => "Olympic Gold: Barcelona '92")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/operation-wolf", :title => "Operation Wolf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ottifants", :title => "The Ottifants")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/outrun", :title => "OutRun")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/outrun-europa", :title => "OutRun Europa")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pac-mania", :title => "Pac-Mania")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/paperboy", :title => "Paperboy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/parlour-games", :title => "Parlour Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/penguin-land", :title => "Penguin Land")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pga-tour-golf", :title => "PGA Tour Golf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/phantasy-star", :title => "Phantasy Star")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pit-pot-the-magical-castle", :title => "Pit Pot: The Magical Castle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pit-fighter", :title => "Pit-Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/populous", :title => "Populous")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/poseidon-wars-3-d", :title => "Poseidon Wars 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/power-strike", :title => "Power Strike")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/power-strike-ii", :title => "Power Strike II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/prince-of-persia", :title => "Prince of Persia")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/psychic-world", :title => "Psychic World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/psycho-fox", :title => "Psycho Fox")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/putt-putter", :title => "Putt & Putter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/quartet", :title => "Quartet")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/quest-for-the-shaven-yak-starring-ren-hok-stimpy", :title => "Quest for the Shaven Yak starring Ren Hoek & Stempy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/r-type", :title => "R-Type")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rainbow-islands", :title => "Rainbow Islands")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rambo-first-blood-part-ii_", :title => "Rambo: First Blood Part II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rampage", :title => "Rampage")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rampart", :title => "Rampart")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rastan", :title => "Rastan")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/renegade", :title => "Renegade")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/road-rash", :title => "Road Rash")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/robocop-3", :title => "RoboCop 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/robocop-versus-the-terminator", :title => "RoboCop Versus the Terminator")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rygar", :title => "Rygar")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/safari-hunt", :title => "Safari Hunt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sagaia", :title => "Sagaia")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sapo-xul-o-mestre-do-kung-fu", :title => "Sapo Xule: O Mestre do Kung Fu")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/scramble-spirits", :title => "Scramble Spirits")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sdi-strategic-defense-initiative", :title => "SDI: Strategic Defense Initiative")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/secret-commando", :title => "Secret Commando")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sega-master-system-included-games", :title => "SEGA Master System (included games)")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sensible-soccer-european-champions-9293-edition", :title => "Sensible Soccer: European Champions: 92/93 Edition")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shadow-dancer", :title => "Shadow Dancer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shadow-of-the-beast", :title => "Shadow of the Beast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shanghai", :title => "Shanghai")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shinobi", :title => "Shinobi")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shooting-gallery_", :title => "Shooting Gallery")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/simpsons-bart-vs-the-space-mutants", :title => "The Simpsons: Bart vs. the Space Mutants")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/simpsons-bart-vs-the-world", :title => "The Simpsons: Bart vs. the World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/smash-tv", :title => "Smash T.V.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/smurfs__", :title => "The Smurfs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/solomons-key", :title => "Solomon's Key")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-blast", :title => "Sonic Blast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-the-hedgehog-chaos", :title => "Sonic the Hedgehog Chaos")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-the-hedgehog-spinball", :title => "Sonic the Hedgehog: Spinball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/space-gun", :title => "Space Gun")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/space-harrier", :title => "Space Harrier")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/speedball", :title => "Speedball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/speedball-2-brutal-deluxe", :title => "Speedball 2: Brutal Deluxe")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spellcaster", :title => "SpellCaster")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spider-man___", :title => "Spider-Man")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spy-vs-spy", :title => "Spy vs. Spy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/star-wars_", :title => "Star Wars")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/street-fighter-ii-special-champion-edition", :title => "Street Fighter II': Special Champion Edition")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/streets-of-rage", :title => "Streets of Rage")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/streets-of-rage-2", :title => "Streets of Rage 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/strider", :title => "Strider")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/strider-2_", :title => "Strider 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/summer-games", :title => "Summer Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/super-kick-off", :title => "Super Kick Off")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/super-monaco-gp", :title => "Super Monaco GP")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/t2-the-arcade-game", :title => "T2: The Arcade Game")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/taitos-super-space-invaders", :title => "Taito's Super Space Invaders")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/taz-mania", :title => "Taz-Mania")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/teddy-boy", :title => "Teddy Boy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/terminator-2-judgment-day_", :title => "Terminator 2: Judgment Day")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/terminator_", :title => "The Terminator")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/thunderblade", :title => "ThunderBlade")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/time-soldiers", :title => "Time Soldiers")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/transbot", :title => "TransBot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/trivial-pursuit", :title => "Trivial Pursuit")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ultima-iv-quest-of-the-avatar", :title => "Ultima IV: Quest of the Avatar")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ultimate-soccer", :title => "Ultimate Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/vigilante", :title => "Vigilante")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/virtua-fighter-animation", :title => "Virtua Fighter Animation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/walter-payton-football", :title => "Walter Payton Football")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wanted", :title => "Wanted")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/where-in-the-world-is-carmen-sandiego", :title => "Where in the World is Carmen Sandiego?")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wimbledon-championship-tennis", :title => "Wimbledon Championship Tennis")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/winter-olympics-lillehammer-94", :title => "Winter Olympics: Lillehammer '94")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wolfchild", :title => "Wolfchild")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy", :title => "Wonder Boy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-iii-the-dragons-trap", :title => "Wonder Boy III: The Dragon's Trap")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-in-monster-land", :title => "Wonder Boy in Monster Land")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-in-monster-world", :title => "Wonder Boy in Monster World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-championship-soccer", :title => "World Championship Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-class-leader-board", :title => "World Class Leader Board")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-cup-usa-94", :title => "World Cup USA 94")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-games", :title => "World Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wwf-wrestlemania-steel-cage-challenge", :title => "WWF Wrestlemania: Steel Cage Challenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/xenon-2-megablast", :title => "Xenon 2: Megablast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/xevious", :title => "Xevious")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ys-the-vanished-omens", :title => "Ys: The Vanished Omens")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zaxxon-3-d", :title => "Zaxxon 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zillion", :title => "Zillion")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zillion-2-tri-formation", :title => "Zillion 2: Tri Formation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zool", :title => "Zool")
end