# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

@sms = System.find_by_name("Sega Master System")
if @sms.present?
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ace-of-aces", :title => "Ace of Aces")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/action-fighter", :title => "Action Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/addams-family___", :title => "The Addams Family")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/aerial-assault", :title => "Aerial Assault")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/after-burner", :title => "After Burner")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/air-rescue", :title => "Air Rescue")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-in-miracle-world", :title => "Alex Kidd in Miracle World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-in-shinobi-world", :title => "Alex Kidd in Shinobi World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-bmx-trial", :title => "Alex Kidd: BMX Trial")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-high-tech-world", :title => "Alex Kidd: High-Tech World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alex-kidd-the-lost-stars", :title => "Alex Kidd: The Lost Stars")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alf", :title => "ALF")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien-storm", :title => "Alien Storm")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien-syndrome", :title => "Alien Syndrome")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/alien_", :title => "Alien 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/altered-beast", :title => "Altered Beast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/andre-agassi-tennis", :title => "Andre Agassi Tennis")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/arcade-smash-hits", :title => "Arcade Smash Hits")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/as-aventuras-da-tv-colosso", :title => "As Aventuras da TV Colosso")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/assault-city", :title => "Assault City")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astro-warrior", :title => "Astro Warrior") 
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astro-warrior-pit-pot", :title => "Astro Warrior / Pit Pot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astrix_", :title => "Asterix")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/astrix-and-the-great-rescue", :title => "Asterix and the Great Rescue")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ayrton-sennas-super-monaco-gp-ii", :title => "Ayrton Senna's Super Monaco GP II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/aztec-adventure", :title => "Aztec Adventure")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/back-to-the-future-part-ii", :title => "Back to the Future Part II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/back-to-the-future-part-iii", :title => "Back to the Future Part III")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/baku-baku-animal", :title => "Baku Baku Animal")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bank-panic", :title => "Bank Panic")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/batman-returns_______", :title => "Batman Returns")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/battle-out-run", :title => "Battle Out Run")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/battletoads-in-battlemaniacs", :title => "Battletoads in Battlemaniacs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/black-belt", :title => "Black Belt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/blade-eagle-3-d", :title => "Blade Eagle 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bomber-raid", :title => "Bomber Raid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bonanza-bros", :title => "Bonanza Bros.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bram-stokers-dracula__", :title => "Bram Stoker's Dracula")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/bubble-bobble", :title => "Bubble Bobble")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/california-games", :title => "California Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/california-games-ii", :title => "California Games II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/captain-silver", :title => "Captain Silver")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chapolim-x-drcula-um-duelo-assustador", :title => "Chapolim x Dracula: Um Duelo Assustador")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chase-hq", :title => "Chase H.Q.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chase-hq-ii-special-criminal-investigation", :title => "Chase H.Q. II: Special Criminal Investigation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cheese-cat-astrophe-starring-speedy-gonzales", :title => "Cheese Cat-Astrophe starring Speedy Gonzales")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/choplifter", :title => "Choplifter!")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chuck-rock", :title => "Chuck Rock")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/chuck-rock-ii-son-of-chuck", :title => "Chuck Rock II: Son of Chuck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cloud-master", :title => "Cloud Master")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/columns", :title => "Columns")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cool-spot", :title => "Cool Spot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cosmic-spacehead", :title => "Cosmic Spacehead")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cyber-shinobi-shinobi-part-2", :title => "The Cyber Shinobi: Shinobi Part 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/cyborg-hunter", :title => "Cyborg Hunter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/danan-the-jungle-fighter", :title => "Danan the Jungle Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dead-angle", :title => "Dead Angle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/deep-duck-trouble-starring-donald-duck", :title => "Deep Duck Trouble starring Donald Duck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/desert-strike-return-to-the-gulf", :title => "Desert Strike: Return to the Gulf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/disneys-ariel-the-little-mermaid", :title => "Disney's Ariel the Little Mermaid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/disneys-bonkers-wax-up", :title => "Disney's Bonkers: Wax Up!")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/double-dragon", :title => "Double Dragon")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/double-hawk", :title => "Double Hawk")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dr-robotniks-mean-bean-machine", :title => "Dr. Robotnik's Mean Bean Machine")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dragon-crystal", :title => "Dragon Crystal")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dragon-the-bruce-lee-story_", :title => "Dragon: The Bruce Lee Story")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dynamite-duke", :title => "Dynamite Duke")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/dynamite-headdy", :title => "Dynamite Headdy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/e-swat-cyber-police", :title => "E-SWAT: Cyber Police")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/earthworm-jim", :title => "Earthworm Jim")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ecco-the-dolphin", :title => "Ecco the Dolphin")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ecco-the-tides-of-time", :title => "Ecco: The Tides of Time")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/enduro-racer", :title => "Enduro Racer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/f16-fighting-falcon", :title => "F16 Fighting Falcon")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantastic-adventures-of-dizzy", :title => "The Fantastic Adventures of Dizzy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone", :title => "Fantasy Zone")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone-ii", :title => "Fantasy Zone II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fantasy-zone-the-maze", :title => "Fantasy Zone: The Maze")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fifa-international-soccer", :title => "FIFA International Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fire-forget-ii", :title => "Fire & Forget II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/fire-ice", :title => "Fire & Ice")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/forgotten-worlds", :title => "Forgotten Worlds")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/g-loc-air-battle", :title => "G-Loc Air Battle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gain-ground", :title => "Gain Ground")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/galactic-protector", :title => "Galactic Protector")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-corridas", :title => "Game Box Serie Corridas")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-esportes", :title => "Game Box Serie Esportes")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/game-box-srie-lutas", :title => "Game Box Serie Lutas")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gangster-town", :title => "Gangster Town")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/gauntlet", :title => "Gauntlet")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/george-foremans-ko-boxing", :title => "George Foreman's KO Boxing")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghost-house", :title => "Ghost House")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghostbusters", :title => "Ghostbusters")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ghouls-n-ghosts", :title => "Ghouls 'N Ghosts")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/global-defense", :title => "Global Defense")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/global-gladiators", :title => "Global Gladiators")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golden-axe", :title => "Golden Axe")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golden-axe-warrior", :title => "Golden Axe Warrior")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/golvellius-valley-of-doom", :title => "Golvellius: Valley of Doom")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/great-volleyball", :title => "Great Volleyball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hang-on-safari-hunt", :title => "Hang On & Safari Hunt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hang-on", :title => "Hang-On")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/heroes-of-the-lance", :title => "Heroes of the Lance")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/hokuto-no-ken_", :title => "Hokuto no Ken")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/impossible-mission", :title => "Impossible Mission")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/incredible-crash-dummies", :title => "The Incredible Crash Dummies")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/incredible-hulk_", :title => "The Incredible Hulk")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/indiana-jones-and-the-last-crusade-the-action-game", :title => "Indiana Jones and the Last Crusade: The Action ...")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ivan-iron-man-stewarts-super-off-road", :title => "Ivan 'Iron Man' Stewart's Super Off Road")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/james-bond-007-the-duel", :title => "James Bond 007: The Duel")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/james-pond-2-codename-robocod", :title => "James Pond 2: Codename: RoboCod")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/jungle-book_", :title => "The Jungle Book")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kenseiden", :title => "Kenseiden")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kings-quest", :title => "King's Quest")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/klax", :title => "Klax")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/krustys-fun-house", :title => "Krusty's Fun House")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/kung-fu-kid", :title => "Kung Fu Kid")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/land-of-illusion-starring-mickey-mouse", :title => "Land of Illusion starring Mickey Mouse")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/laser-ghost", :title => "Laser Ghost")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/legend-of-illusion-starring-mickey-mouse", :title => "Legend of Illusion starring Mickey Mouse")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lemmings", :title => "Lemmings")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lion-king", :title => "The Lion King")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lord-of-the-sword", :title => "Lord of the Sword")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/lucky-dime-caper-starring-donald-duck", :title => "The Lucky Dime Caper starring Donald Duck")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/marble-madness", :title => "Marble Madness")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/master-of-darkness", :title => "Master of Darkness")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/maze-hunter-3-d", :title => "Maze Hunter 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mercs", :title => "Mercs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/michael-jacksons-moonwalker", :title => "Michael Jackson's Moonwalker")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mickeys-ultimate-challenge", :title => "Mickey's Ultimate Challenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/micro-machines", :title => "Micro Machines")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/miracle-warriors-seal-of-the-dark-lord", :title => "Miracle Warriors: Seal of the Dark Lord")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/missile-defense-3-d", :title => "Missile Defense 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/monopoly", :title => "Monopoly")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/montezumas-revenge", :title => "Montezuma's Revenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat", :title => "Mortal Kombat")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat-3", :title => "Mortal Kombat 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mortal-kombat-ii", :title => "Mortal Kombat II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ms-pac-man", :title => "Ms. Pac-Man")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/my-hero", :title => "My Hero")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/mnica-no-castelo-do-drago", :title => "Monica no Castelo do Dragao")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/new-zealand-story", :title => "The New Zealand Story")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ninja", :title => "The Ninja")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/olympic-gold-barcelona-92", :title => "Olympic Gold: Barcelona '92")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/operation-wolf", :title => "Operation Wolf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ottifants", :title => "The Ottifants")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/outrun", :title => "OutRun")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/outrun-europa", :title => "OutRun Europa")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pac-mania", :title => "Pac-Mania")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/paperboy", :title => "Paperboy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/parlour-games", :title => "Parlour Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/penguin-land", :title => "Penguin Land")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pga-tour-golf", :title => "PGA Tour Golf")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/phantasy-star", :title => "Phantasy Star")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pit-pot-the-magical-castle", :title => "Pit Pot: The Magical Castle")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/pit-fighter", :title => "Pit-Fighter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/populous", :title => "Populous")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/poseidon-wars-3-d", :title => "Poseidon Wars 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/power-strike", :title => "Power Strike")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/power-strike-ii", :title => "Power Strike II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/prince-of-persia", :title => "Prince of Persia")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/psychic-world", :title => "Psychic World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/psycho-fox", :title => "Psycho Fox")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/putt-putter", :title => "Putt & Putter")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/quartet", :title => "Quartet")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/quest-for-the-shaven-yak-starring-ren-hok-stimpy", :title => "Quest for the Shaven Yak starring Ren Hoek & Stempy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/r-type", :title => "R-Type")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rainbow-islands", :title => "Rainbow Islands")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rambo-first-blood-part-ii_", :title => "Rambo: First Blood Part II")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rampage", :title => "Rampage")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rampart", :title => "Rampart")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rastan", :title => "Rastan")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/renegade", :title => "Renegade")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/road-rash", :title => "Road Rash")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/robocop-3", :title => "RoboCop 3")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/robocop-versus-the-terminator", :title => "RoboCop Versus the Terminator")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/rygar", :title => "Rygar")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/safari-hunt", :title => "Safari Hunt")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sagaia", :title => "Sagaia")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sapo-xul-o-mestre-do-kung-fu", :title => "Sapo Xule: O Mestre do Kung Fu")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/scramble-spirits", :title => "Scramble Spirits")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sdi-strategic-defense-initiative", :title => "SDI: Strategic Defense Initiative")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/secret-commando", :title => "Secret Commando")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sega-master-system-included-games", :title => "SEGA Master System (included games)")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sensible-soccer-european-champions-9293-edition", :title => "Sensible Soccer: European Champions: 92/93 Edition")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shadow-dancer", :title => "Shadow Dancer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shadow-of-the-beast", :title => "Shadow of the Beast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shanghai", :title => "Shanghai")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shinobi", :title => "Shinobi")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/shooting-gallery_", :title => "Shooting Gallery")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/simpsons-bart-vs-the-space-mutants", :title => "The Simpsons: Bart vs. the Space Mutants")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/simpsons-bart-vs-the-world", :title => "The Simpsons: Bart vs. the World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/smash-tv", :title => "Smash T.V.")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/smurfs__", :title => "The Smurfs")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/solomons-key", :title => "Solomon's Key")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-blast", :title => "Sonic Blast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-the-hedgehog-chaos", :title => "Sonic the Hedgehog Chaos")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/sonic-the-hedgehog-spinball", :title => "Sonic the Hedgehog: Spinball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/space-gun", :title => "Space Gun")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/space-harrier", :title => "Space Harrier")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/speedball", :title => "Speedball")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/speedball-2-brutal-deluxe", :title => "Speedball 2: Brutal Deluxe")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spellcaster", :title => "SpellCaster")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spider-man___", :title => "Spider-Man")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/spy-vs-spy", :title => "Spy vs. Spy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/star-wars_", :title => "Star Wars")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/street-fighter-ii-special-champion-edition", :title => "Street Fighter II': Special Champion Edition")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/streets-of-rage", :title => "Streets of Rage")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/streets-of-rage-2", :title => "Streets of Rage 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/strider", :title => "Strider")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/strider-2_", :title => "Strider 2")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/summer-games", :title => "Summer Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/super-kick-off", :title => "Super Kick Off")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/super-monaco-gp", :title => "Super Monaco GP")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/t2-the-arcade-game", :title => "T2: The Arcade Game")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/taitos-super-space-invaders", :title => "Taito's Super Space Invaders")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/taz-mania", :title => "Taz-Mania")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/teddy-boy", :title => "Teddy Boy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/terminator-2-judgment-day_", :title => "Terminator 2: Judgment Day")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/terminator_", :title => "The Terminator")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/thunderblade", :title => "ThunderBlade")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/time-soldiers", :title => "Time Soldiers")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/transbot", :title => "TransBot")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/trivial-pursuit", :title => "Trivial Pursuit")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ultima-iv-quest-of-the-avatar", :title => "Ultima IV: Quest of the Avatar")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ultimate-soccer", :title => "Ultimate Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/vigilante", :title => "Vigilante")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/virtua-fighter-animation", :title => "Virtua Fighter Animation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/walter-payton-football", :title => "Walter Payton Football")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wanted", :title => "Wanted")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/where-in-the-world-is-carmen-sandiego", :title => "Where in the World is Carmen Sandiego?")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wimbledon-championship-tennis", :title => "Wimbledon Championship Tennis")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/winter-olympics-lillehammer-94", :title => "Winter Olympics: Lillehammer '94")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wolfchild", :title => "Wolfchild")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy", :title => "Wonder Boy")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-iii-the-dragons-trap", :title => "Wonder Boy III: The Dragon's Trap")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-in-monster-land", :title => "Wonder Boy in Monster Land")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wonder-boy-in-monster-world", :title => "Wonder Boy in Monster World")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-championship-soccer", :title => "World Championship Soccer")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-class-leader-board", :title => "World Class Leader Board")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-cup-usa-94", :title => "World Cup USA 94")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/world-games", :title => "World Games")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/wwf-wrestlemania-steel-cage-challenge", :title => "WWF Wrestlemania: Steel Cage Challenge")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/xenon-2-megablast", :title => "Xenon 2: Megablast")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/xevious", :title => "Xevious")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/ys-the-vanished-omens", :title => "Ys: The Vanished Omens")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zaxxon-3-d", :title => "Zaxxon 3-D")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zillion", :title => "Zillion")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zillion-2-tri-formation", :title => "Zillion 2: Tri Formation")
  Game.create(:system_id => @sms.id, :moby_url => "/game/sega-master-system/zool", :title => "Zool")
end

@nes = System.find_by_name("Nintendo Entertainment System")
if @nes.present?
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/89-denn-kysei-uranai", :title => "'89 Denno Kyusei Uranai") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/1942", :title => "1942")
	Game.create(:system_id => @nes.id, :moby_url => "/game/nes/720", :title => "720")
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/action-52", :title => "Action 52") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/addams-family-pugsleys-scavenger-hunt", :title => "The Addams Family: Pugsley's Scavenger Hunt")
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventure-island", :title => "Adventure Island") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventure-island-ii-aliens-in-paradise", :title => "Adventure Island II: Aliens in Paradise") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-captain-comic", :title => "The Adventures of Captain Comic") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-dino-riki", :title => "Adventures of Dino-Riki") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-gilligans-island", :title => "The Adventures of Gilligan's Island") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-lolo", :title => "Adventures of Lolo") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-lolo-3", :title => "Adventures of Lolo 3") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/adventures-of-rad-gravity", :title => "The Adventures of Rad Gravity") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/after-burner", :title => "After Burner") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/after-burner-ii", :title => "After Burner II") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/alien-syndrome", :title => "Alien Syndrome") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/altered-beast", :title => "Altered Beast") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/amagon", :title => "Amagon") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/anticipation", :title => "Anticipation") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/arch-rivals", :title => "Arch Rivals") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/archon-the-light-and-the-dark", :title => "Archon: The Light and the Dark") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/arkanoid", :title => "Arkanoid") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/arkanoid-ii-revenge-of-doh", :title => "Arkanoid II: Revenge of Doh") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/back-to-the-future", :title => "Back to the Future") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bad-dudes", :title => "Bad Dudes") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bad-street-brawler", :title => "Bad Street Brawler") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bandit-kings-of-ancient-china", :title => "Bandit Kings of Ancient China") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bards-tale-ii-the-destiny-knight", :title => "The Bard's Tale II: The Destiny Knight") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/battle-chess", :title => "Battle Chess") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/battle-of-olympus", :title => "The Battle of Olympus") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/battletoads", :title => "Battletoads") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bible-adventures", :title => "Bible Adventures") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/blades-of-steel", :title => "Blades of Steel") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bloody-warriors-shan-go-no-gyakush", :title => "Bloody Warriors: Shan Go no Gyakushu") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/blues-brothers", :title => "The Blues Brothers") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bonks-adventure", :title => "Bonk's Adventure") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/boulder-dash", :title => "Boulder Dash") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bram-stokers-dracula__", :title => "Bram Stoker's Dracula") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bubble-bobble", :title => "Bubble Bobble") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/bump-n-jump", :title => "Bump 'N' Jump") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/burgertime", :title => "BurgerTime") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/cabal", :title => "Cabal") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/california-games", :title => "California Games") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/castlevania", :title => "Castlevania") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/castlevania-iii-draculas-curse-", :title => "Castlevania III: Dracula's Curse ") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/caveman-ugh-lympics", :title => "Caveman Ugh-Lympics") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/championship-lode-runner", :title => "Championship Lode Runner") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/choplifter", :title => "Choplifter!") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/classic-concentration", :title => "Classic Concentration") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/commando", :title => "Commando") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/contra", :title => "Contra") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/cool-world", :title => "Cool World") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/crystalis", :title => "Crystalis") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/cybernoid-the-fighting-machine", :title => "Cybernoid: The Fighting Machine") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/darkwing-duck", :title => "Darkwing Duck") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dash-galaxy-in-the-alien-asylum", :title => "Dash Galaxy in the Alien Asylum") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/days-of-thunder", :title => "Days of Thunder") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/deep-dungeon-iv-kuro-no-yjutsushi", :title => "Deep Dungeon IV: Kuro no Yojutsushi") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/defender-of-the-crown", :title => "Defender of the Crown") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/demon-sword", :title => "Demon Sword") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dig-dug", :title => "Dig Dug") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dig-dug-ii-trouble-in-paradise", :title => "Dig Dug II: Trouble in Paradise") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/digital-devil-story-megami-tensei", :title => "Digital Devil Story: Megami Tensei") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/disneys-aladdin", :title => "Disney's Aladdin") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dizzy-prince-of-the-yolkfolk", :title => "Dizzy: Prince of the Yolkfolk") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/donkey-kong", :title => "Donkey Kong") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/donkey-kong-3", :title => "Donkey Kong 3") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/donkey-kong-jr-jr-sansuu-lesson", :title => "Donkey Kong Jr. / Jr. Sansuu Lesson") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/donkey-kong-jr-math", :title => "Donkey Kong Jr. Math") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/donkey-kong-junior", :title => "Donkey Kong Junior") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/double-dragon", :title => "Double Dragon") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/double-dragon-ii-the-revenge", :title => "Double Dragon II: The Revenge") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/double-dragon-iii-the-sacred-stones", :title => "Double Dragon III: The Sacred Stones") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/double-strike", :title => "Double Strike") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/downtown-nekketsu-koushinkyoku-soreyuke-daiundoukai", :title => "Downtown Nekketsu Koushinkyoku - Soreyuke Daiun...") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dr-mario", :title => "Dr. Mario") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dragon-wars", :title => "Dragon Wars") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dragons-of-flame", :title => "Dragons of Flame") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/duck-hunt", :title => "Duck Hunt") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/duck-tales-2", :title => "Duck Tales 2") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/dj-vu-a-nightmare-comes-true", :title => "Deja Vu: A Nightmare Comes True!!") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/elevator-action", :title => "Elevator Action") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/elite", :title => "Elite") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/excitebike", :title => "Excitebike") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/exodus-ultima-iii", :title => "Exodus: Ultima III") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/f-15-strike-eagle", :title => "F-15 Strike Eagle") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/fantastic-adventures-of-dizzy", :title => "The Fantastic Adventures of Dizzy") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/fantasy-zone", :title => "Fantasy Zone") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/faxanadu", :title => "Faxanadu") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/final-fantasy-ii", :title => "Final Fantasy II") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/final-fantasy-iii", :title => "Final Fantasy III") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/fist-of-the-north-star", :title => "Fist of the North Star") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/flight-of-the-intruder", :title => "Flight of the Intruder") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/galaga", :title => "Galaga") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/galaxian", :title => "Galaxian") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/gauntlet", :title => "Gauntlet") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/gauntlet-ii", :title => "Gauntlet II") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/gemfire", :title => "Gemfire") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/genghis-khan", :title => "Genghis Khan") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/genghis-khan-ii-clan-of-the-grey-wolf", :title => "Genghis Khan II: Clan of the Grey Wolf") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ghostbusters", :title => "Ghostbusters") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ghosts-n-goblins", :title => "Ghosts 'N Goblins") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/gradius", :title => "Gradius") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/guardian-legend", :title => "The Guardian Legend") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/gyruss", :title => "Gyruss") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/heroes-of-the-lance", :title => "Heroes of the Lance") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/high-speed", :title => "High Speed") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/hillsfar", :title => "Hillsfar") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/hokuto-no-ken", :title => "Hokuto no Ken") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/hook", :title => "Hook") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/hostage-rescue-mission", :title => "Hostage: Rescue Mission") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ice-hockey", :title => "Ice Hockey") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ikari-warriors", :title => "Ikari Warriors") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/immortal", :title => "The Immortal") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/impossible-mission-ii", :title => "Impossible Mission II") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/indiana-jones-and-the-last-crusade-the-action-game", :title => "Indiana Jones and the Last Crusade: The Action ...") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/indiana-jones-and-the-temple-of-doom", :title => "Indiana Jones and the Temple of Doom") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ivan-iron-man-stewarts-super-off-road", :title => "Ivan 'Iron Man' Stewart's Super Off Road") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/joe-mac-caveman-ninja", :title => "Joe & Mac: Caveman Ninja") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/john-elways-quarterback", :title => "John Elway's Quarterback") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/jordan-vs-bird-one-on-one", :title => "Jordan vs. Bird: One-on-One") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/joust", :title => "Joust") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kabuki-quantum-fighter", :title => "Kabuki: Quantum Fighter") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/karateka", :title => "Karateka") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/karnov", :title => "Karnov") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kid-dracula", :title => "Kid Dracula") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kid-icarus", :title => "Kid Icarus") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kings-of-the-beach", :title => "Kings of the Beach") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kirbys-adventure", :title => "Kirby's Adventure") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/kung-fu-master", :title => "Kung-Fu Master") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/lempereur", :title => "L'Empereur") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/last-action-hero", :title => "Last Action Hero") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/law-of-the-west", :title => "Law of the West") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/legend-of-zelda", :title => "The Legend of Zelda") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/lemmings", :title => "Lemmings") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/lethal-weapon", :title => "Lethal Weapon") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/life-force", :title => "Life Force") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/little-league-baseball-championship-series", :title => "Little League Baseball Championship Series") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/lode-runner", :title => "Lode Runner") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mule", :title => "M.U.L.E.") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/muscle", :title => "M.U.S.C.L.E.") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/magic-candle", :title => "The Magic Candle") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mahjong__", :title => "Mahjong") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/maniac-mansion", :title => "Maniac Mansion") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/marble-madness", :title => "Marble Madness") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mario-bros", :title => "Mario Bros.") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mario-is-missing", :title => "Mario is Missing!") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mega-man-2", :title => "Mega Man 2") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mega-man-3", :title => "Mega Man 3") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mega-man-4", :title => "Mega Man 4") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mega-man-5", :title => "Mega Man 5") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mega-man-6", :title => "Mega Man 6") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/metal-fighter", :title => "Metal Fighter") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/metal-gear", :title => "Metal Gear") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/metal-max", :title => "Metal Max") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/metroid", :title => "Metroid") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/micro-machines", :title => "Micro Machines") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/might-and-magic-book-i", :title => "Might and Magic: Book I") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mighty-final-fight", :title => "Mighty Final Fight") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mike-tysons-punch-out", :title => "Mike Tyson's Punch-Out!!") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/monopoly", :title => "Monopoly") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ms-pac-man", :title => "Ms. Pac-Man") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/mutant-virus", :title => "The Mutant Virus") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/nes-open-tournament-golf", :title => "NES Open Tournament Golf") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ninja-gaiden-ii-the-dark-sword-of-chaos", :title => "Ninja Gaiden II: The Dark Sword of Chaos") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/nobunagas-ambition", :title => "Nobunaga's Ambition") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/nobunagas-ambition-ii", :title => "Nobunaga's Ambition II") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/north-south", :title => "North & South") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/operation-europe-path-to-victory-1939-45", :title => "Operation Europe: Path to Victory 1939-45") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/operation-wolf", :title => "Operation Wolf") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/overlord-", :title => "Overlord") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/pac-land", :title => "Pac-Land") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/pac-man", :title => "Pac-Man") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/paperboy", :title => "Paperboy") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/paperboy-2", :title => "Paperboy 2") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/pipe-dream", :title => "Pipe Dream") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/pool-of-radiance", :title => "Pool of Radiance") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/popeye-no-eigo-asobi", :title => "Popeye no Eigo Asobi") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/power-blade", :title => "Power Blade") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/prince-of-persia", :title => "Prince of Persia") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/pyramid", :title => "Pyramid") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/qix", :title => "QIX") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rad-racer", :title => "Rad Racer") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/raid-2020", :title => "Raid 2020") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/raid-on-bungeling-bay", :title => "Raid on Bungeling Bay") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rampage", :title => "Rampage") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rampart", :title => "Rampart") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/river-city-ransom", :title => "River City Ransom") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/robocop-3", :title => "RoboCop 3") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rocket-ranger", :title => "Rocket Ranger") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rodland", :title => "Rodland") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rollerball", :title => "Rollerball") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/rushn-attack", :title => "Rush'n Attack") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/shadowgate", :title => "Shadowgate") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/shinobi", :title => "Shinobi") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/shockwave", :title => "Shockwave") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/shufflepuck-cafe", :title => "Shufflepuck Cafe") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/sid-meiers-pirates", :title => "Sid Meier's Pirates!") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/silent-service", :title => "Silent Service") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/simpsons-bart-vs-the-space-mutants", :title => "The Simpsons: Bart vs. the Space Mutants") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/skate-or-die", :title => "Skate or Die") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ski-or-die", :title => "Ski or Die") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/sky-shark", :title => "Sky Shark") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/slalom", :title => "Slalom") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/space-harrier", :title => "Space Harrier") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/space-invaders-", :title => "Space Invaders") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/speedball", :title => "Speedball") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/spy-hunter", :title => "Spy Hunter") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/spy-vs-spy", :title => "Spy vs. Spy") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/stargate", :title => "Stargate") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/super-mario-bros", :title => "Super Mario Bros.") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/super-mario-bros-2", :title => "Super Mario Bros. 2") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/super-mario-bros-3", :title => "Super Mario Bros. 3") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/super-sprint", :title => "Super Sprint") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tales-of-the-unknown-volume-i-the-bards-tale", :title => "Tales of the Unknown: Volume I - The Bard's Tale") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/target-renegade", :title => "Target: Renegade") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tecmo-bowl", :title => "Tecmo Bowl") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tecmo-super-bowl", :title => "Tecmo Super Bowl") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/teenage-mutant-ninja-turtles", :title => "Teenage Mutant Ninja Turtles") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/teenage-mutant-ninja-turtles-iii-the-manhattan-project", :title => "Teenage Mutant Ninja Turtles III: The Manhattan...") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tetris-2", :title => "Tetris 2") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/thexder", :title => "Thexder") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/three-stooges", :title => "The Three Stooges") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/times-of-lore", :title => "Times of Lore") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tiny-toon-adventures", :title => "Tiny Toon Adventures") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/top-gun-the-second-mission", :title => "Top Gun: The Second Mission") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/tower-toppler", :title => "Tower Toppler") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/treasure-island-dizzy", :title => "Treasure Island Dizzy") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/trojan", :title => "Trojan") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ultima-iv-quest-of-the-avatar", :title => "Ultima IV: Quest of the Avatar") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ultima-v-warriors-of-destiny", :title => "Ultima V: Warriors of Destiny") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/uncharted-waters", :title => "Uncharted Waters") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/uninvited", :title => "Uninvited") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/urban-champion", :title => "Urban Champion") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/valis-the-fantasm-soldier", :title => "Valis: The Fantasm Soldier") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/vegas-dream", :title => "Vegas Dream") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/walt-disneys-the-jungle-book", :title => "Walt Disney's The Jungle Book") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/wayne-gretzky-hockey", :title => "Wayne Gretzky Hockey") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/where-in-time-is-carmen-sandiego", :title => "Where in Time is Carmen Sandiego?") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/win-lose-or-draw", :title => "Win, Lose, or Draw") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/winter-games", :title => "Winter Games") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/wizardry-knight-of-diamonds-the-second-scenario", :title => "Wizardry: Knight of Diamonds - The Second Scenario") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/wizardry-legacy-of-llylgamyn-the-third-scenario", :title => "Wizardry: Legacy of Llylgamyn - The Third Scenario") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/wizardry-proving-grounds-of-the-mad-overlord", :title => "Wizardry: Proving Grounds of the Mad Overlord") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/world-games", :title => "World Games") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/yoshis-cookie", :title => "Yoshi's Cookie") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/ys-iii-wanderers-from-ys", :title => "Ys III: Wanderers from Ys") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/yume-penguin-monogatari", :title => "Yume Penguin Monogatari") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/zelda-ii-the-adventure-of-link", :title => "Zelda II: The Adventure of Link") 
  Game.create(:system_id => @nes.id, :moby_url => "/game/nes/zodas-revenge-star-tropics-iii", :title => "Zoda's Revenge: Star Tropics II")
end